//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.tameenak.technoSys.com/")]
    public partial class AIMSFault
    {
        
        private string faultStringField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultString
        {
            get
            {
                return this.faultStringField;
            }
            set
            {
                this.faultStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.tameenak.technoSys.com/")]
    public partial class polResponse
    {
        
        private byte[] policyResFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] policyResFile
        {
            get
            {
                return this.policyResFileField;
            }
            set
            {
                this.policyResFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.tameenak.technoSys.com/")]
    public partial class policyRequest
    {
        
        private string authenticationField;
        
        private byte[] policyReqFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] policyReqFile
        {
            get
            {
                return this.policyReqFileField;
            }
            set
            {
                this.policyReqFileField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.tameenak.technoSys.com/", ConfigurationName="ServiceReference.TameenakImpl")]
    public interface TameenakImpl
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.tameenak.technoSys.com/TameenakImpl/PolicyRequest", ReplyAction="http://service.tameenak.technoSys.com/TameenakImpl/PolicyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.AIMSFault), Action="http://service.tameenak.technoSys.com/TameenakImpl/Policy/Fault/AIMSFault", Name="AIMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.PolicyResponse> PolicyAsync(ServiceReference.PolicyRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.tameenak.technoSys.com/TameenakImpl/GetTotalMembersRequest", ReplyAction="http://service.tameenak.technoSys.com/TameenakImpl/GetTotalMembersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.GetTotalMembersResponse> GetTotalMembersAsync(ServiceReference.GetTotalMembersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.tameenak.technoSys.com/TameenakImpl/GQuoteRequest", ReplyAction="http://service.tameenak.technoSys.com/TameenakImpl/GQuoteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.AIMSFault), Action="http://service.tameenak.technoSys.com/TameenakImpl/GQuote/Fault/AIMSFault", Name="AIMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.GQuoteResponse1> GQuoteAsync(ServiceReference.GQuoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.tameenak.technoSys.com/TameenakImpl/QuotationRequest", ReplyAction="http://service.tameenak.technoSys.com/TameenakImpl/QuotationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.AIMSFault), Action="http://service.tameenak.technoSys.com/TameenakImpl/Quotation/Fault/AIMSFault", Name="AIMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.QuotationResponse> QuotationAsync(ServiceReference.QuotationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.tameenak.technoSys.com/TameenakImpl/GPolicyRequest", ReplyAction="http://service.tameenak.technoSys.com/TameenakImpl/GPolicyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.AIMSFault), Action="http://service.tameenak.technoSys.com/TameenakImpl/GPolicy/Fault/AIMSFault", Name="AIMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.GPolicyResponse> GPolicyAsync(ServiceReference.GPolicyRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.tameenak.technoSys.com/TameenakImpl/GetCCHIStatusRequest", ReplyAction="http://service.tameenak.technoSys.com/TameenakImpl/GetCCHIStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.GetCCHIStatusResponse> GetCCHIStatusAsync(ServiceReference.GetCCHIStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Policy", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class PolicyRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.policyRequest PolicyRequest;
        
        public PolicyRequest1()
        {
        }
        
        public PolicyRequest1(ServiceReference.policyRequest PolicyRequest)
        {
            this.PolicyRequest = PolicyRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyResponse", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class PolicyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.polResponse @return;
        
        public PolicyResponse()
        {
        }
        
        public PolicyResponse(ServiceReference.polResponse @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.tameenak.technoSys.com/")]
    public partial class smeRequest
    {
        
        private string authenticationField;
        
        private byte[] requestFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] requestFile
        {
            get
            {
                return this.requestFileField;
            }
            set
            {
                this.requestFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.tameenak.technoSys.com/")]
    public partial class smeResponse
    {
        
        private byte[] resFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] resFile
        {
            get
            {
                return this.resFileField;
            }
            set
            {
                this.resFileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTotalMembers", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class GetTotalMembersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.smeRequest arg0;
        
        public GetTotalMembersRequest()
        {
        }
        
        public GetTotalMembersRequest(ServiceReference.smeRequest arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTotalMembersResponse", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class GetTotalMembersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.smeResponse @return;
        
        public GetTotalMembersResponse()
        {
        }
        
        public GetTotalMembersResponse(ServiceReference.smeResponse @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.tameenak.technoSys.com/")]
    public partial class gQuotRequest
    {
        
        private string authenticationField;
        
        private byte[] quoteFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] quoteFile
        {
            get
            {
                return this.quoteFileField;
            }
            set
            {
                this.quoteFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.tameenak.technoSys.com/")]
    public partial class gQuoteResponse
    {
        
        private byte[] resFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] resFile
        {
            get
            {
                return this.resFileField;
            }
            set
            {
                this.resFileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GQuote", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class GQuoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.gQuotRequest GQuote;
        
        public GQuoteRequest()
        {
        }
        
        public GQuoteRequest(ServiceReference.gQuotRequest GQuote)
        {
            this.GQuote = GQuote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GQuoteResponse", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class GQuoteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.gQuoteResponse @return;
        
        public GQuoteResponse1()
        {
        }
        
        public GQuoteResponse1(ServiceReference.gQuoteResponse @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.tameenak.technoSys.com/")]
    public partial class quoteRequest
    {
        
        private string authenticationField;
        
        private byte[] quoteFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] quoteFile
        {
            get
            {
                return this.quoteFileField;
            }
            set
            {
                this.quoteFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.tameenak.technoSys.com/")]
    public partial class quoteResponse
    {
        
        private byte[] resFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] resFile
        {
            get
            {
                return this.resFileField;
            }
            set
            {
                this.resFileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Quotation", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class QuotationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.quoteRequest QuoteRequest;
        
        public QuotationRequest()
        {
        }
        
        public QuotationRequest(ServiceReference.quoteRequest QuoteRequest)
        {
            this.QuoteRequest = QuoteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QuotationResponse", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class QuotationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.quoteResponse @return;
        
        public QuotationResponse()
        {
        }
        
        public QuotationResponse(ServiceReference.quoteResponse @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.tameenak.technoSys.com/")]
    public partial class gPolicyRequest
    {
        
        private string authenticationField;
        
        private byte[] policyReqFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] policyReqFile
        {
            get
            {
                return this.policyReqFileField;
            }
            set
            {
                this.policyReqFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.tameenak.technoSys.com/")]
    public partial class gPolResponse
    {
        
        private byte[] resFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] resFile
        {
            get
            {
                return this.resFileField;
            }
            set
            {
                this.resFileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GPolicy", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class GPolicyRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.gPolicyRequest GPolicy;
        
        public GPolicyRequest1()
        {
        }
        
        public GPolicyRequest1(ServiceReference.gPolicyRequest GPolicy)
        {
            this.GPolicy = GPolicy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GPolicyResponse", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class GPolicyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.gPolResponse @return;
        
        public GPolicyResponse()
        {
        }
        
        public GPolicyResponse(ServiceReference.gPolResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCCHIStatus", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class GetCCHIStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.smeRequest arg0;
        
        public GetCCHIStatusRequest()
        {
        }
        
        public GetCCHIStatusRequest(ServiceReference.smeRequest arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCCHIStatusResponse", WrapperNamespace="http://service.tameenak.technoSys.com/", IsWrapped=true)]
    public partial class GetCCHIStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.tameenak.technoSys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.smeResponse @return;
        
        public GetCCHIStatusResponse()
        {
        }
        
        public GetCCHIStatusResponse(ServiceReference.smeResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface TameenakImplChannel : ServiceReference.TameenakImpl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class TameenakImplClient : System.ServiceModel.ClientBase<ServiceReference.TameenakImpl>, ServiceReference.TameenakImpl
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TameenakImplClient() : 
                base(TameenakImplClient.GetDefaultBinding(), TameenakImplClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TameenakImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TameenakImplClient(EndpointConfiguration endpointConfiguration) : 
                base(TameenakImplClient.GetBindingForEndpoint(endpointConfiguration), TameenakImplClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TameenakImplClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TameenakImplClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TameenakImplClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TameenakImplClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TameenakImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.PolicyResponse> ServiceReference.TameenakImpl.PolicyAsync(ServiceReference.PolicyRequest1 request)
        {
            return base.Channel.PolicyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.PolicyResponse> PolicyAsync(ServiceReference.policyRequest PolicyRequest)
        {
            ServiceReference.PolicyRequest1 inValue = new ServiceReference.PolicyRequest1();
            inValue.PolicyRequest = PolicyRequest;
            return ((ServiceReference.TameenakImpl)(this)).PolicyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetTotalMembersResponse> ServiceReference.TameenakImpl.GetTotalMembersAsync(ServiceReference.GetTotalMembersRequest request)
        {
            return base.Channel.GetTotalMembersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetTotalMembersResponse> GetTotalMembersAsync(ServiceReference.smeRequest arg0)
        {
            ServiceReference.GetTotalMembersRequest inValue = new ServiceReference.GetTotalMembersRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.TameenakImpl)(this)).GetTotalMembersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GQuoteResponse1> ServiceReference.TameenakImpl.GQuoteAsync(ServiceReference.GQuoteRequest request)
        {
            return base.Channel.GQuoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GQuoteResponse1> GQuoteAsync(ServiceReference.gQuotRequest GQuote)
        {
            ServiceReference.GQuoteRequest inValue = new ServiceReference.GQuoteRequest();
            inValue.GQuote = GQuote;
            return ((ServiceReference.TameenakImpl)(this)).GQuoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.QuotationResponse> ServiceReference.TameenakImpl.QuotationAsync(ServiceReference.QuotationRequest request)
        {
            return base.Channel.QuotationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.QuotationResponse> QuotationAsync(ServiceReference.quoteRequest QuoteRequest)
        {
            ServiceReference.QuotationRequest inValue = new ServiceReference.QuotationRequest();
            inValue.QuoteRequest = QuoteRequest;
            return ((ServiceReference.TameenakImpl)(this)).QuotationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GPolicyResponse> ServiceReference.TameenakImpl.GPolicyAsync(ServiceReference.GPolicyRequest1 request)
        {
            return base.Channel.GPolicyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GPolicyResponse> GPolicyAsync(ServiceReference.gPolicyRequest GPolicy)
        {
            ServiceReference.GPolicyRequest1 inValue = new ServiceReference.GPolicyRequest1();
            inValue.GPolicy = GPolicy;
            return ((ServiceReference.TameenakImpl)(this)).GPolicyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetCCHIStatusResponse> ServiceReference.TameenakImpl.GetCCHIStatusAsync(ServiceReference.GetCCHIStatusRequest request)
        {
            return base.Channel.GetCCHIStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetCCHIStatusResponse> GetCCHIStatusAsync(ServiceReference.smeRequest arg0)
        {
            ServiceReference.GetCCHIStatusRequest inValue = new ServiceReference.GetCCHIStatusRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference.TameenakImpl)(this)).GetCCHIStatusAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TameenakImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TameenakImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://46.235.95.59:7788/TameenakWSProd/TameenakImplPort");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TameenakImplClient.GetBindingForEndpoint(EndpointConfiguration.TameenakImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TameenakImplClient.GetEndpointAddress(EndpointConfiguration.TameenakImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            TameenakImplPort,
        }
    }
}
