//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedGulfService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://aggregators.MedGulfService.com.sa/TameenK/", ConfigurationName="MedGulfService.TameenkSoap")]
    public interface TameenkSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aggregators.MedGulfService.com.sa/TameenK/Quotes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> QuotesAsync(string Username, string Password, string JsonRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aggregators.MedGulfService.com.sa/TameenK/Policy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> PolicyAsync(string Username, string Password, string JsonRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aggregators.MedGulfService.com.sa/TameenK/PolicySchedule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> PolicyScheduleAsync(string Username, string Password, string JsonRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aggregators.MedGulfService.com.sa/TameenK/VehicleImagesDownload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> VehicleImagesDownloadAsync(string Username, string Password, string ReferenceId, string PolicyNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aggregators.MedGulfService.com.sa/TameenK/UpdateCustomCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> UpdateCustomCardAsync(string Username, string Password, string JsonRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aggregators.MedGulfService.com.sa/TameenK/PolicyCancellation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> PolicyCancellationAsync(string Username, string Password, string JsonRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface TameenkSoapChannel : MedGulfService.TameenkSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class TameenkSoapClient : System.ServiceModel.ClientBase<MedGulfService.TameenkSoap>, MedGulfService.TameenkSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TameenkSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TameenkSoapClient.GetBindingForEndpoint(endpointConfiguration), TameenkSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TameenkSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TameenkSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TameenkSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TameenkSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TameenkSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> QuotesAsync(string Username, string Password, string JsonRequest)
        {
            return base.Channel.QuotesAsync(Username, Password, JsonRequest);
        }
        
        public System.Threading.Tasks.Task<string> PolicyAsync(string Username, string Password, string JsonRequest)
        {
            return base.Channel.PolicyAsync(Username, Password, JsonRequest);
        }
        
        public System.Threading.Tasks.Task<string> PolicyScheduleAsync(string Username, string Password, string JsonRequest)
        {
            return base.Channel.PolicyScheduleAsync(Username, Password, JsonRequest);
        }
        
        public System.Threading.Tasks.Task<string> VehicleImagesDownloadAsync(string Username, string Password, string ReferenceId, string PolicyNo)
        {
            return base.Channel.VehicleImagesDownloadAsync(Username, Password, ReferenceId, PolicyNo);
        }
        
        public System.Threading.Tasks.Task<string> UpdateCustomCardAsync(string Username, string Password, string JsonRequest)
        {
            return base.Channel.UpdateCustomCardAsync(Username, Password, JsonRequest);
        }
        
        public System.Threading.Tasks.Task<string> PolicyCancellationAsync(string Username, string Password, string JsonRequest)
        {
            return base.Channel.PolicyCancellationAsync(Username, Password, JsonRequest);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TameenkSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TameenkSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TameenkSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://onlinetest.MedGulfService.com.sa/Tameenk/WebServices/Tameenk.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TameenkSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://onlinetest.MedGulfService.com.sa/Tameenk/WebServices/Tameenk.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TameenkSoap,
            
            TameenkSoap12,
        }
    }
}
